export interface EnvConfig {
  llmProvider: 'anthropic' | 'openai' | 'google';
  llmApiKey: string;
  githubAppId: string;
  githubAppPrivateKeyPath: string;
  githubWebhookSecret: string;
  signalIngestionHmacSecret: string;
  dashboardAuthToken: string;
  minioAccessKey: string;
  minioSecretKey: string;
  postgresPassword: string;
  allowedOrigins: string;
  autoApproveRiskThreshold: number;
  deploymentWebhookUrl?: string;
  deploymentWebhookSecret?: string;
  logLevel?: string;
}

export function generateEnvFile(cfg: EnvConfig): string {
  const llmKeyVar =
    cfg.llmProvider === 'anthropic'
      ? 'ANTHROPIC_API_KEY'
      : cfg.llmProvider === 'openai'
        ? 'OPENAI_API_KEY'
        : 'GOOGLE_API_KEY';

  return `# ============================================================
# Pullmint - Environment Configuration
# Generated by create-pullmint on ${new Date().toISOString()}
# ============================================================

# ------------------------------------------------------------
# LLM Provider
# ------------------------------------------------------------
LLM_PROVIDER=${cfg.llmProvider}
${llmKeyVar}=${cfg.llmApiKey}

# ------------------------------------------------------------
# GitHub App
# ------------------------------------------------------------
GITHUB_APP_ID=${cfg.githubAppId}
GITHUB_APP_PRIVATE_KEY_PATH=${cfg.githubAppPrivateKeyPath}
GITHUB_WEBHOOK_SECRET=${cfg.githubWebhookSecret}

# ------------------------------------------------------------
# Internal signal ingestion
# ------------------------------------------------------------
SIGNAL_INGESTION_HMAC_SECRET=${cfg.signalIngestionHmacSecret}

# ------------------------------------------------------------
# Dashboard
# ------------------------------------------------------------
DASHBOARD_AUTH_TOKEN=${cfg.dashboardAuthToken}
ALLOWED_ORIGINS=${cfg.allowedOrigins}

# ------------------------------------------------------------
# MinIO (object storage - stores PR diffs)
# ------------------------------------------------------------
MINIO_ACCESS_KEY=${cfg.minioAccessKey}
MINIO_SECRET_KEY=${cfg.minioSecretKey}

# ------------------------------------------------------------
# PostgreSQL - password only; DATABASE_URL is set by Compose
# ------------------------------------------------------------
POSTGRES_PASSWORD=${cfg.postgresPassword}

# ------------------------------------------------------------
# Risk scoring
# ------------------------------------------------------------
# PRs with a final risk score below this value are auto-approved
AUTO_APPROVE_RISK_THRESHOLD=${cfg.autoApproveRiskThreshold}

# ------------------------------------------------------------
# Deployment webhooks (optional)
# ------------------------------------------------------------
${cfg.deploymentWebhookUrl ? `DEPLOYMENT_WEBHOOK_URL=${cfg.deploymentWebhookUrl}` : '# DEPLOYMENT_WEBHOOK_URL='}
${cfg.deploymentWebhookSecret ? `DEPLOYMENT_WEBHOOK_SECRET=${cfg.deploymentWebhookSecret}` : '# DEPLOYMENT_WEBHOOK_SECRET='}

# ------------------------------------------------------------
# Logging
# ------------------------------------------------------------
LOG_LEVEL=${cfg.logLevel ?? 'info'}

# ------------------------------------------------------------
# Optional model overrides (uncomment to override defaults)
# ------------------------------------------------------------
# LLM_ARCHITECTURE_MODEL=claude-sonnet-4-6
# LLM_SECURITY_MODEL=claude-sonnet-4-6
# LLM_PERFORMANCE_MODEL=claude-haiku-4-5-20251001
# LLM_MAINTAINABILITY_MODEL=claude-haiku-4-5-20251001

# ------------------------------------------------------------
# Optional tuning
# ------------------------------------------------------------
# INCREMENTAL_ANALYSIS_THRESHOLD=0.5
# MULTI_AGENT_MIN_DIFF_LINES=200
# LLM_MAX_DIFF_CHARS_ARCHITECTURE=100000
# LLM_MAX_DIFF_CHARS_SECURITY=100000
# LLM_MAX_DIFF_CHARS_PERFORMANCE=60000
# LLM_MAX_DIFF_CHARS_STYLE=60000
`;
}
